export const ASTON_MARTIN = require("./aston-martin-db12.jpg")
export const DBX_707 = require("./dbx-707.png")
export const DBX_707_2 = require("./dbx707-2.png")
export const DOWNLOAD = require('./download.png')
export const IMAGE =require("./Image.png")
export const LOGO_1 = require("./Logo-3.png")
export const LOGO_2 =require("./Logo-4.png")
export const CONTENT = require("./content.png")
export const CONTENT_2 = require("./content-2.png")
export const CONTENT_3 = require("./content-3.png")

